# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v2nZ3U34tt6i1ZIJu4vtJcQ0fh22GuJc
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from datetime import datetime, timedelta
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder

# -*- coding: utf-8 -*-
"""
SmartStock ARAOUAA - Version simple (console)
Système de gestion et prévision de stock avec 5 fonctionnalités
"""

import random
from datetime import datetime, timedelta

# ======================================================
# 1. DONNÉES FICTIVES
# ======================================================

fournisseurs = ["Sahara Fruit", "CBN Food", "Bridge Food", "Atlantic Nuts",
                 "Pacific Fruit", "Soufiane Nuts", "Shams Bean", "Tagir Nature"]

produits_liste = ["Lentilles", "Pois chiches", "Fèves", "Haricots blancs",
                   "Cumin", "Poivre noir", "Curcuma", "Cannelle"]

stock = []
for i, produit in enumerate(produits_liste, start=1):
    stock.append({
        "id": f"P{i:03d}",
        "produit": produit,
        "fournisseur": random.choice(fournisseurs),
        "quantite": random.randint(5, 300),
        "seuil_min": random.randint(30, 80),
        "prix": round(random.uniform(5, 50), 2),
        "jours_peremption": random.randint(-5, 120),  # négatif = déjà périmé
        "demande_jour": round(random.uniform(2, 15), 1),
    })


# ======================================================
# 2. GESTION DIGITALE DU STOCK
# ======================================================

def afficher_stock():
    print("\n--- ÉTAT DU STOCK ---")
    print(f"{'ID':<6}{'Produit':<16}{'Fournisseur':<16}{'Qté':<8}{'Seuil':<8}{'Prix':<8}{'Périme dans':<12}")
    for p in stock:
        print(f"{p['id']:<6}{p['produit']:<16}{p['fournisseur']:<16}{p['quantite']:<8}"
              f"{p['seuil_min']:<8}{p['prix']:<8}{p['jours_peremption']} j")


def entree_stock(id_produit, quantite):
    for p in stock:
        if p["id"] == id_produit:
            p["quantite"] += quantite
            print(f"✅ Entrée de {quantite} kg pour {p['produit']}. Nouveau stock: {p['quantite']}")
            return
    print("Produit introuvable.")


def sortie_stock(id_produit, quantite):
    for p in stock:
        if p["id"] == id_produit:
            p["quantite"] = max(0, p["quantite"] - quantite)
            print(f"✅ Sortie de {quantite} kg pour {p['produit']}. Nouveau stock: {p['quantite']}")
            return
    print("Produit introuvable.")


# ======================================================
# 3. ALERTES (STOCK BAS + PÉREMPTION)
# ======================================================

def verifier_alertes():
    print("\n--- ALERTES ---")
    alerte_trouvee = False
    for p in stock:
        messages = []
        if p["quantite"] <= p["seuil_min"]:
            messages.append("⚠️ Stock bas")
        if p["jours_peremption"] < 0:
            messages.append("❌ Périmé")
        elif p["jours_peremption"] <= 15:
            messages.append("⏳ Péremption proche")

        if messages:
            alerte_trouvee = True
            print(f"{p['id']} - {p['produit']} : {' | '.join(messages)}")

    if not alerte_trouvee:
        print("✅ Aucune alerte, tout va bien.")


# ======================================================
# 4. DASHBOARD LOGISTIQUE
# ======================================================

def dashboard():
    print("\n--- DASHBOARD LOGISTIQUE ---")
    valeur_totale = sum(p["quantite"] * p["prix"] for p in stock)
    stock_bas = sum(1 for p in stock if p["quantite"] <= p["seuil_min"])
    perimes = sum(1 for p in stock if p["jours_peremption"] < 0)

    print(f"Nombre de produits      : {len(stock)}")
    print(f"Valeur totale du stock  : {valeur_totale:,.2f} MAD")
    print(f"Produits en stock bas   : {stock_bas}")
    print(f"Produits périmés        : {perimes}")

    print("\nValeur de stock par fournisseur :")
    par_fournisseur = {}
    for p in stock:
        par_fournisseur[p["fournisseur"]] = par_fournisseur.get(p["fournisseur"], 0) + p["quantite"] * p["prix"]
    for f, v in sorted(par_fournisseur.items(), key=lambda x: -x[1]):
        print(f"  {f:<16}: {v:,.2f} MAD")


# ======================================================
# 5. PRÉVISION DE LA DEMANDE
# ======================================================

def prevoir_demande(id_produit, jours=7):
    for p in stock:
        if p["id"] == id_produit:
            historique = [max(0, p["demande_jour"] + random.uniform(-2, 2)) for _ in range(14)]
            moyenne = sum(historique) / len(historique)
            prevision = [round(moyenne + random.uniform(-1, 1), 1) for _ in range(jours)]

            print(f"\n--- Prévision de la demande : {p['produit']} ---")
            print(f"Moyenne historique : {moyenne:.1f} kg/jour")
            for i, val in enumerate(prevision, start=1):
                date = (datetime.today() + timedelta(days=i)).strftime("%d/%m")
                print(f"  {date} : {val} kg")
            return
    print("Produit introuvable.")


# ======================================================
# 6. RECOMMANDATION DE DÉCISION (modèle de règles)
# ======================================================

def recommander_decision():
    print("\n--- RECOMMANDATIONS (modèle de décision) ---")
    for p in stock:
        ratio_stock = p["quantite"] / p["seuil_min"]
        jours_couverture = p["quantite"] / p["demande_jour"]

        if p["jours_peremption"] < 0 or ratio_stock < 0.3:
            decision = "🔴 Déstocker / Écouler urgent"
        elif p["quantite"] <= p["seuil_min"]:
            decision = "🟠 Réapprovisionner"
        elif p["jours_peremption"] <= 30:
            decision = "🟡 Surveiller (péremption proche)"
        elif jours_couverture > 60:
            decision = "🔵 Réduire les commandes futures"
        else:
            decision = "🟢 Stock optimal"

        print(f"{p['id']} - {p['produit']:<16}: {decision}")


# ======================================================
# MENU PRINCIPAL
# ======================================================

def menu():
    while True:
        print("\n===== SmartStock ARAOUAA =====")
        print("1. Afficher le stock")
        print("2. Entrée de stock")
        print("3. Sortie de stock")
        print("4. Voir les alertes")
        print("5. Dashboard logistique")
        print("6. Prévision de la demande")
        print("7. Recommandations ML")
        print("0. Quitter")

        choix = input("Choix : ")

        if choix == "1":
            afficher_stock()
        elif choix == "2":
            id_p = input("ID du produit : ")
            qte = int(input("Quantité : "))
            entree_stock(id_p, qte)
        elif choix == "3":
            id_p = input("ID du produit : ")
            qte = int(input("Quantité : "))
            sortie_stock(id_p, qte)
        elif choix == "4":
            verifier_alertes()
        elif choix == "5":
            dashboard()
        elif choix == "6":
            id_p = input("ID du produit : ")
            prevoir_demande(id_p)
        elif choix == "7":
            recommander_decision()
        elif choix == "0":
            print("Au revoir 👋")
            break
        else:
            print("Choix invalide.")


if __name__ == "__main__":
    afficher_stock()
    menu()

!pip install -q streamlit pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# import random
# import matplotlib.pyplot as plt
# from datetime import datetime, timedelta
# 
# # =========================================================
# # CONFIGURATION
# # =========================================================
# 
# st.set_page_config(
#     page_title="SmartStock ARAOUAA",
#     page_icon="📦",
#     layout="wide"
# )
# 
# # =========================================================
# # DONNÉES
# # =========================================================
# 
# fournisseurs = [
#     "Sahara Fruit", "CBN Food", "Bridge Food", "Atlantic Nuts",
#     "Pacific Fruit", "Soufiane Nuts", "Shams Bean", "Tagir Nature"
# ]
# 
# produits_liste = [
#     "Lentilles", "Pois chiches", "Fèves", "Haricots blancs",
#     "Cumin", "Poivre noir", "Curcuma", "Cannelle"
# ]
# 
# # Création du stock
# if "stock" not in st.session_state:
# 
#     stock = []
# 
#     for i, produit in enumerate(produits_liste, start=1):
# 
#         stock.append({
#             "ID": f"P{i:03d}",
#             "Produit": produit,
#             "Fournisseur": random.choice(fournisseurs),
#             "Quantité (kg)": random.randint(5, 300),
#             "Seuil minimum": random.randint(30, 80),
#             "Prix (MAD/kg)": round(random.uniform(5, 50), 2),
#             "Jours avant péremption": random.randint(-5, 120),
#             "Demande (kg/jour)": round(random.uniform(2, 15), 1)
#         })
# 
#     st.session_state.stock = stock
# 
# 
# # =========================================================
# # TITRE
# # =========================================================
# 
# st.title("📦 SmartStock ARAOUAA")
# 
# st.markdown(
#     "### Système digital de gestion et de prévision des stocks"
# )
# 
# st.markdown("---")
# 
# 
# # =========================================================
# # SIDEBAR
# # =========================================================
# 
# st.sidebar.title("☰ Menu")
# 
# page = st.sidebar.radio(
#     "Navigation",
#     [
#         "📊 Dashboard",
#         "📦 Gestion du stock",
#         "➕ Entrée de stock",
#         "➖ Sortie de stock",
#         "⚠️ Alertes",
#         "📈 Prévision de la demande",
#         "🤖 Recommandations"
#     ]
# )
# 
# 
# # =========================================================
# # DATAFRAME
# # =========================================================
# 
# df = pd.DataFrame(st.session_state.stock)
# 
# 
# # =========================================================
# # DASHBOARD
# # =========================================================
# 
# if page == "📊 Dashboard":
# 
#     st.header("📊 Dashboard logistique")
# 
#     valeur_totale = sum(
#         p["Quantité (kg)"] * p["Prix (MAD/kg)"]
#         for p in st.session_state.stock
#     )
# 
#     stock_bas = sum(
#         p["Quantité (kg)"] <= p["Seuil minimum"]
#         for p in st.session_state.stock
#     )
# 
#     perimes = sum(
#         p["Jours avant péremption"] < 0
#         for p in st.session_state.stock
#     )
# 
#     produits = len(st.session_state.stock)
# 
#     # KPI
#     col1, col2, col3, col4 = st.columns(4)
# 
#     col1.metric(
#         "📦 Produits",
#         produits
#     )
# 
#     col2.metric(
#         "💰 Valeur du stock",
#         f"{valeur_totale:,.2f} MAD"
#     )
# 
#     col3.metric(
#         "⚠️ Stock bas",
#         stock_bas
#     )
# 
#     col4.metric(
#         "❌ Produits périmés",
#         perimes
#     )
# 
#     st.markdown("---")
# 
#     # Graphique quantité
#     st.subheader("📊 Quantité disponible par produit")
# 
#     graphique = df[
#         ["Produit", "Quantité (kg)"]
#     ].set_index("Produit")
# 
#     st.bar_chart(graphique)
# 
#     st.markdown("---")
# 
#     # Valeur par fournisseur
#     st.subheader("💰 Valeur du stock par fournisseur")
# 
#     valeur_fournisseur = (
#         df["Quantité (kg)"] * df["Prix (MAD/kg)"]
#     )
# 
#     df_graph = pd.DataFrame({
#         "Fournisseur": df["Fournisseur"],
#         "Valeur (MAD)": valeur_fournisseur
#     })
# 
#     df_graph = (
#         df_graph.groupby("Fournisseur")["Valeur (MAD)"]
#         .sum()
#         .sort_values(ascending=False)
#     )
# 
#     st.bar_chart(df_graph)
# 
# 
# # =========================================================
# # GESTION DU STOCK
# # =========================================================
# 
# elif page == "📦 Gestion du stock":
# 
#     st.header("📦 État actuel du stock")
# 
#     st.dataframe(
#         df,
#         use_container_width=True,
#         hide_index=True
#     )
# 
#     st.info(
#         "Les données présentées correspondent au stock utilisé "
#         "dans la démonstration SmartStock ARAOUAA."
#     )
# 
# 
# # =========================================================
# # ENTREE DE STOCK
# # =========================================================
# 
# elif page == "➕ Entrée de stock":
# 
#     st.header("➕ Entrée de stock")
# 
#     produits = [
#         p["ID"] + " - " + p["Produit"]
#         for p in st.session_state.stock
#     ]
# 
#     produit_selectionne = st.selectbox(
#         "Sélectionner le produit",
#         produits
#     )
# 
#     quantite = st.number_input(
#         "Quantité à ajouter (kg)",
#         min_value=1,
#         step=1
#     )
# 
#     if st.button("✅ Enregistrer l'entrée"):
# 
#         id_produit = produit_selectionne.split(" - ")[0]
# 
#         for p in st.session_state.stock:
# 
#             if p["ID"] == id_produit:
# 
#                 p["Quantité (kg)"] += quantite
# 
#                 st.success(
#                     f"Entrée de {quantite} kg enregistrée pour "
#                     f"{p['Produit']}."
#                 )
# 
#                 st.rerun()
# 
# 
# # =========================================================
# # SORTIE DE STOCK
# # =========================================================
# 
# elif page == "➖ Sortie de stock":
# 
#     st.header("➖ Sortie de stock")
# 
#     produits = [
#         p["ID"] + " - " + p["Produit"]
#         for p in st.session_state.stock
#     ]
# 
#     produit_selectionne = st.selectbox(
#         "Sélectionner le produit",
#         produits
#     )
# 
#     quantite = st.number_input(
#         "Quantité à sortir (kg)",
#         min_value=1,
#         step=1
#     )
# 
#     if st.button("✅ Enregistrer la sortie"):
# 
#         id_produit = produit_selectionne.split(" - ")[0]
# 
#         for p in st.session_state.stock:
# 
#             if p["ID"] == id_produit:
# 
#                 if quantite > p["Quantité (kg)"]:
# 
#                     st.error(
#                         "❌ Quantité demandée supérieure au stock disponible."
#                     )
# 
#                 else:
# 
#                     p["Quantité (kg)"] -= quantite
# 
#                     st.success(
#                         f"Sortie de {quantite} kg enregistrée pour "
#                         f"{p['Produit']}."
#                     )
# 
#                     st.rerun()
# 
# 
# # =========================================================
# # ALERTES
# # =========================================================
# 
# elif page == "⚠️ Alertes":
# 
#     st.header("⚠️ Alertes logistiques")
# 
#     alertes = []
# 
#     for p in st.session_state.stock:
# 
#         messages = []
# 
#         if p["Quantité (kg)"] <= p["Seuil minimum"]:
#             messages.append("⚠️ Stock bas")
# 
#         if p["Jours avant péremption"] < 0:
#             messages.append("❌ Produit périmé")
# 
#         elif p["Jours avant péremption"] <= 15:
#             messages.append("⏳ Péremption proche")
# 
#         if messages:
# 
#             alertes.append({
#                 "ID": p["ID"],
#                 "Produit": p["Produit"],
#                 "Quantité (kg)": p["Quantité (kg)"],
#                 "Jours avant péremption":
#                     p["Jours avant péremption"],
#                 "Alerte": " | ".join(messages)
#             })
# 
#     if alertes:
# 
#         st.dataframe(
#             pd.DataFrame(alertes),
#             use_container_width=True,
#             hide_index=True
#         )
# 
#     else:
# 
#         st.success(
#             "✅ Aucune alerte détectée."
#         )
# 
# 
# # =========================================================
# # PREVISION DE LA DEMANDE
# # =========================================================
# 
# elif page == "📈 Prévision de la demande":
# 
#     st.header("📈 Prévision de la demande")
# 
#     produits = [
#         p["ID"] + " - " + p["Produit"]
#         for p in st.session_state.stock
#     ]
# 
#     produit_selectionne = st.selectbox(
#         "Sélectionner le produit",
#         produits
#     )
# 
#     jours = st.slider(
#         "Nombre de jours à prévoir",
#         min_value=3,
#         max_value=30,
#         value=7
#     )
# 
#     if st.button("📈 Générer la prévision"):
# 
#         id_produit = produit_selectionne.split(" - ")[0]
# 
#         produit = None
# 
#         for p in st.session_state.stock:
# 
#             if p["ID"] == id_produit:
#                 produit = p
#                 break
# 
#         historique = [
#             max(
#                 0,
#                 produit["Demande (kg/jour)"]
#                 + random.uniform(-2, 2)
#             )
#             for _ in range(14)
#         ]
# 
#         moyenne = sum(historique) / len(historique)
# 
#         prevision = [
#             round(
#                 moyenne + random.uniform(-1, 1),
#                 1
#             )
#             for _ in range(jours)
#         ]
# 
#         dates = [
#             (datetime.today() + timedelta(days=i)).strftime("%d/%m")
#             for i in range(1, jours + 1)
#         ]
# 
#         resultat = pd.DataFrame({
#             "Date": dates,
#             "Demande prévue (kg)": prevision
#         })
# 
#         st.success(
#             f"Demande moyenne estimée : {moyenne:.1f} kg/jour"
#         )
# 
#         st.dataframe(
#             resultat,
#             use_container_width=True,
#             hide_index=True
#         )
# 
#         st.subheader("📊 Évolution de la demande prévue")
# 
#         st.line_chart(
#             resultat.set_index("Date")
#         )
# 
# 
# # =========================================================
# # RECOMMANDATIONS
# # =========================================================
# 
# elif page == "🤖 Recommandations":
# 
#     st.header("🤖 Recommandations de décision")
# 
#     recommandations = []
# 
#     for p in st.session_state.stock:
# 
#         ratio_stock = (
#             p["Quantité (kg)"] /
#             p["Seuil minimum"]
#         )
# 
#         jours_couverture = (
#             p["Quantité (kg)"] /
#             p["Demande (kg/jour)"]
#         )
# 
#         if (
#             p["Jours avant péremption"] < 0
#             or ratio_stock < 0.3
#         ):
# 
#             decision = "🔴 Déstocker / Écouler urgent"
# 
#         elif p["Quantité (kg)"] <= p["Seuil minimum"]:
# 
#             decision = "🟠 Réapprovisionner"
# 
#         elif p["Jours avant péremption"] <= 30:
# 
#             decision = "🟡 Surveiller"
# 
#         elif jours_couverture > 60:
# 
#             decision = "🔵 Réduire les commandes futures"
# 
#         else:
# 
#             decision = "🟢 Stock optimal"
# 
#         recommandations.append({
#             "ID": p["ID"],
#             "Produit": p["Produit"],
#             "Stock (kg)": p["Quantité (kg)"],
#             "Seuil": p["Seuil minimum"],
#             "Péremption": p["Jours avant péremption"],
#             "Couverture (jours)": round(
#                 jours_couverture,
#                 1
#             ),
#             "Décision": decision
#         })
# 
#     df_recommandations = pd.DataFrame(
#         recommandations
#     )
# 
#     st.dataframe(
#         df_recommandations,
#         use_container_width=True,
#         hide_index=True
#     )
# 
#     st.markdown("---")
# 
#     st.info(
#         "ℹ️ Les recommandations sont basées sur des règles "
#         "de décision liées au niveau de stock, au seuil minimum, "
#         "à la péremption et à la couverture du stock."
#     )

!streamlit run app.py &>/content/logs.txt &

# The Streamlit application is running in the background.
# Its output, including the URL to access it, is redirected to /content/logs.txt.
# Let's display the content of the logs to find the URL.
with open('/content/logs.txt', 'r') as f:
    logs = f.read()
print(logs)

print("\nLook for a URL starting with 'External URL:' or a link provided by Colab (usually appears above the cell output) to access your Streamlit app.")

!pip install -q streamlit pyngrok

# Lancer Streamlit
!streamlit run app.py --server.port 8501 > /content/logs.txt 2>&1 &

import time
time.sleep(5)

# Afficher les logs
!cat /content/logs.txt

!pkill -f streamlit

!streamlit run app.py --server.port 8501 > /content/logs.txt 2>&1 &

!cat /content/logs.txt

!pkill -f streamlit

!streamlit run app.py --server.port 8501 > /content/logs.txt 2>&1 &

!cat /content/logs.txt

from google.colab.output import eval_js

print(eval_js("google.colab.kernel.proxyPort(8501)"))

!streamlit run app.py --server.port 8501 > /content/logs.txt 2>&1 &

from google.colab.output import eval_js
print(eval_js("google.colab.kernel.proxyPort(8501)"))
